SolucionTaller/MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SolucionTaller/MVC/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using Negocio;

namespace MVC.Controllers
{
    public class BaseController : Controller
    {
        protected readonly IUnitOfWork _unitOfWork;
        public BaseController  (IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
    }
}

SolucionTaller/MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System.Diagnostics;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SolucionTaller/MVC/Controllers/SeguridadController.cs
using Datos.Modelos;
using Datos.Modelos.ViewModel;
using Microsoft.AspNetCore.Mvc;
using MVC.Util;
using Negocio;

namespace MVC.Controllers
{
    public class SeguridadController : BaseController
    {
        protected readonly IConfiguration _configuration;
        int count = 0;
        public SeguridadController(IUnitOfWork unitOfWork,IConfiguration configuration) : base(unitOfWork)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login([FromForm] Usuario usuario)
        {
            var resultado = await _unitOfWork.usuarioNegocio.ValidateUser(usuario);
            if(resultado==null)
            {
                count++;
                return RedirectToAction("Index");
            }
            else if(count>2)
            {
                usuario.Bloqueado = true;
                _unitOfWork.usuarioNegocio.UpdateBloqueado(usuario);
                ViewBag.MensajeError = "Se bloqueo su cuenta";
            }
            else
            {
                return RedirectToAction("Index", "Taller");
            }
            return View();
        }
        public IActionResult StartRecovery()
        {
            RecoveryViewModel recoveryViewModel = new();
            return View(recoveryViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> StartRecovery(RecoveryViewModel recoveryViewModel)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View(recoveryViewModel);
                }
                Common common = new();
                string token=common.GetSHA256(Guid.NewGuid().ToString());
                Usuario usuario=await _unitOfWork.usuarioNegocio.ObtenerUsuarioPorEmail(recoveryViewModel.Email);
                if(usuario!=null)
                {
                    usuario.TokenRecovery = token;
                    _unitOfWork.usuarioNegocio.UpdateToken(usuario);
                    await _unitOfWork.CommitAsync();
                    var UrlBase = _configuration["Url"];
                    var urlFinal = UrlBase + "Seguridad/Recovery?token=" + token;
                    await common.SendEmailAsync(usuario.Email, urlFinal);
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View();
        }
        public async Task<IActionResult> Recovery(string token)
        {
            RecoveryPasswordViewModel recoveryPasswordViewModel = new();
            recoveryPasswordViewModel.Token = token;
            if(recoveryPasswordViewModel.Token==null && recoveryPasswordViewModel.Token.Trim().Equals(""))
            {
                return View("Index");
            }
            Usuario usuario = await _unitOfWork.usuarioNegocio.ObtenerUsuarioPorToken(recoveryPasswordViewModel.Token);
            if(usuario==null)
            {
                ViewBag.Error = "Tu token ha expirado";
                return View("Index");
            }
            return View(recoveryPasswordViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Recovery(RecoveryPasswordViewModel recoveryPasswordViewModel)
        {
            try
            {
                Usuario usuario = await _unitOfWork.usuarioNegocio.ObtenerUsuarioPorToken(recoveryPasswordViewModel.Token);
                if(usuario!=null)
                { 
                   usuario.Clave=recoveryPasswordViewModel.Clave;
                    usuario.Bloqueado = false;
                    _unitOfWork.usuarioNegocio.UpdatePasswordHabilitar(usuario);
                    await _unitOfWork.CommitAsync();
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
            ViewBag.Message = "La clave se ha modificado con exito";
            return View(recoveryPasswordViewModel);
        }
    }
}

SolucionTaller/MVC/Controllers/TallerController.cs
using Microsoft.AspNetCore.Mvc;
using Negocio;

namespace MVC.Controllers
{
    public class TallerController : BaseController
    {
        public TallerController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {

        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

SolucionTaller/MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SolucionTaller/MVC/Views/Seguridad/Index.cshtml
@model Datos.Modelos.Usuario

@{
    ViewData["Title"] = "Index";
}
<div>
    @ViewBag.MensajeError
</div>
<h4>Usuario</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" id="txtEmail" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" id="txtClave" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"  />
            </div>
        </form>
          
  
    </div>
</div>

<div>
    <a asp-action="StartRecovery" asp-controller="Seguridad">Olvidaste tu clave</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
        @*<script>
            $("#btnLogin").click(function()
           {
            var usuarioBody = {

                Email: $("#txtEmail").val(),
                Clave: $("#txtClave").val(),
              
            }
            $.ajax({
                url: '@Url.Action("Login","Seguridad")',
                method: "POST",
                data: JSON.stringify(usuarioBody),
                datatype: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data) {
                        window.location.replace(urlRetornar);
                        //  location.reload();
                    }
                }
            })
           });

        </script>*@

}

SolucionTaller/MVC/Views/Seguridad/Recovery.cshtml
@model Datos.Modelos.ViewModel.RecoveryPasswordViewModel
@{
    ViewData["Title"] = "Recovery";
}

<h1>Recovery</h1>
<div class="row">
    <div class="col-md-6 offset-3">
        <div class="form-style">
            <form action="@Url.Content("~/Seguridad/Recovery")" method="post">
                @Html.HiddenFor(d=>d.Token)
                <label>Escribe tu nueva contraseña</label>
                @Html.PasswordFor(d=>d.Clave,new {@class="form-control"})
                @Html.ValidationMessageFor(d=>d.Clave,null,new {style="color:red;"})
                <label>Vuelve a escribir la contraseña</label>
                @Html.PasswordFor(d=>d.Clave2,new {@class="form-control"})
                @Html.ValidationMessageFor(d=>d.Clave2,null,new {style="color:red;"})
                <br />
                <div class="text-primary">
                    <button class="btn btn-primary">Recuperar</button>
                </div>
            </form>

        </div>

    </div>

</div>

SolucionTaller/MVC/Views/Seguridad/StartRecovery.cshtml
@model Datos.Modelos.ViewModel.RecoveryViewModel
@{
    ViewData["Title"] = "StartRecovery";
}
<div class="row">
      <div class="col-md-6 offset-3">
             <div class="form-style">
            <form action="@Url.Content("~/Seguridad/StartRecovery")" method="post">
                <label>Escribe tu correo electronico</label>
                @Html.TextBoxFor(d=>d.Email,null,new {@class="form-control"})
                @Html.ValidationMessageFor(d=>d.Email,null,new {style="color:red;"})
                <br/>
                <div class="text-primary">
                        <button class="btn btn-primary">Recuperar</button>
                </div>
            </form>

             </div>

      </div>

</div>

SolucionTaller/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SolucionTaller/MVC/Views/Taller/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>